### ISSUE TITLE
Add ability to exclude vulnerabilities by command line or via file

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/ahab#10]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

Similar to what we did in `nancy`, add the ability to exclude vulnerabilities from failing a build!

https://github.com/sonatype-nexus-community/nancy/pull/30

https://github.com/sonatype-nexus-community/nancy/pull/28

https://github.com/sonatype-nexus-community/nancy/pull/35

https://github.com/sonatype-nexus-community/nancy/pull/29

* **What feature or behavior is this required for?**

This will allow someone to review what vulnerabilities they are affected by, and then exclude the ones they don't find a risk to their project.

* **How could we solve this issue? (Not knowing is okay!)**

I would imagine the best way is to take the functionality we wrote in Nancy, and make it so that Ahab can just leverage it, that way if other projects want to implement this in the future, they can easily do so!

* **Anything else?**

FUN!

cc @bhamail / @DarthHater / @ken-duck

**Comment by zendern** [comment]
Good call, that makes sense. Regarding reusing nancy code. Whats the thoughts there?? Create a shared library or just simply import nancy as a depenency and use those classes directly??

**Comment by DarthHater** [comment]
We already import `nancy` for quite a bit of `ahab`, so yeah, just probably take the exclusion stuff from `nancy` and put it somewhere so it's more useful to other projects :) 

We could create some shared library, if we really wanted to, but I'm fine with `nancy` having all the power, as she's really doing all the work, anyways :)
