### ISSUE TITLE
Add a description to the repo

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/ahab#11]
* **What are you trying to do?**
Make it so that the project is a little more discoverable. Right now you have to navigate into the project to know what it is exactly.

![image](https://user-images.githubusercontent.com/1099906/70438999-09fbd080-1a5d-11ea-8226-00d366b33b85.png)
^^^ View from sonatype-nexus-community listing

![image](https://user-images.githubusercontent.com/1099906/70439037-1d0ea080-1a5d-11ea-93f3-934b9b5815ee.png)
^^^ View from search

* **How could we solve this issue? (Not knowing is okay!)**
Add a description :) 

cc @bhamail / @DarthHater / @ken-duck

**Comment by DarthHater** [comment]
I took a quick lil jab at this, feel free to suggest changes here!

**Comment by zendern** [comment]
![image](https://user-images.githubusercontent.com/1099906/70470596-5cf37900-1a99-11ea-8b81-2521fdfe8cdc.jpg)

Looks good to me but of course made me read the readme and realize this is out of date now that we do apk too.

**Comment by zendern** [comment]
![image](https://user-images.githubusercontent.com/1099906/74108191-a3229280-4b45-11ea-945b-96db44080ee7.png)
I see it got updated....going to close this. 👍
