### ISSUE TITLE
Remove mac binaries from goreleaser

### ISSUE THREAD

**Issue by zendern** [sonatype-nexus-community/ahab#36]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
So ahab scan docker containers at build time, yah?? well macosx running in docker isn't really a thing so producing binaries for mac (aka darwin) i a little confusing at best.  

* **What feature or behavior is this required for?**
Just clean things up a little

* **How could we solve this issue? (Not knowing is okay!)**
Should be able to fiddle the goreleaser configs so that these are no longer output. Windows (even though not yet supported but after #32 it will be) and linux binaries must remain. 

* **Anything else?**

cc @bhamail / @DarthHater / @ken-duck

**Comment by bhamail** [comment]
:+1:
