### ISSUE TITLE
publish MacOS binaries

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/ahab#72]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I'm trying to run ahab on my Mac

* **What feature or behavior is this required for?**
I'm extracting package list from a Docker container, but it's easier to avoid installing ahab inside the container by running it directly from the host OS (a Mac in my case):
`docker run --rm my-docker-image dpkg-query --show --showformat='${Package} ${Version}\n' | ahab --package-manager dpkg`

* **How could we solve this issue? (Not knowing is okay!)**
I tested by building ahab myself, it works
now it's just about providing a binary to users instead of letting them build ahab

* **Anything else?**

cc @bhamail / @DarthHater / @ken-duck

**Comment by bhamail** [comment]
Should be fixed by: https://github.com/sonatype-nexus-community/ahab/commit/384fcaeab7f6ea3b960d64a07a3b8d0cf7400600

Please holler if not (publishing now).

**Comment by hboutemy** [comment]
it works as expected: it's nice to have a pre-built binary that displays `Ahab version: 0.2.7`

thank you @bhamail
